#coding: utf-8
namespace :sac do
  namespace :subject do
    desc "Add municipals for Region 52 (Moscow oblast)"
    task :AddSubjectsForRegion52 => :environment do
      country_id = 100 # Россия
      district_id = 101 # Центральный федеральный округ
      region_id = 52 # Московская область
      Subject.create([
        {name: 'Балашиха, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Белоомут, городское поселение', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Воскресенский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Дзержинский', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Дмитровский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Долгопрудный', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Домодедово, городской округ', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Дубна, наукоград', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Егорьевский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Железнодорожный, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Жуковский', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Звенигород', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Ивантеевка', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Истринский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Каширский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Климовск', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Клинский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Коломенский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Королёв', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Котельники', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Красногорский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Ленинский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Лобня, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Лосино-Петровский, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Лотошинский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Луховицкий муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Люберецкий муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Люберцы', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Можайск', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Мытищи, городское поселение', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Мытищинский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Наро-Фоминский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Обухово, городское поселение', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Одинцовский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Озерский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Орехово-Зуево, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Орехово-Зуевский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Павлово-Посадский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Подольск', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Подольский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Протвино', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Пущино', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Раменский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Реутов', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Ржавки, городское поселение', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Рошаль, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Сергиево-Посадский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Серпухов', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Серпуховский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Солнечногорский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Ступинский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Тучково, городское поселение Рузского района', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Успенское, cельское поселение Одинцовского муниципального района', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Фрязино', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Химки, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Чеховский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Шатурский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Шаховской муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Щербинка', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Щёлково, городское поселение', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Щёлковский муниципальный район', country_id: country_id, district_id: district_id, region_id: region_id},
        {name: 'Электросталь, городской округ', country_id: country_id, district_id: district_id, region_id: 0},
        {name: 'Зарайский муниципальный район', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Волоколамский муниципальный район', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Талдомский муниципальный район', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Коломна, городской округ', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Красноармейск, городской округ', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Серебряно-Прудский муниципальный район', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Рузский муниципальный район', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Пушкинский муниципальный район', country_id: 100, district_id: 101, region_id: 52},
        {name: 'Ногинский муниципальный район', country_id: 100, district_id: 101, region_id: 52},
      ])
    end
    # Subject.find().update_attribute(region_id: 0)
  end
end
