development:
  adapter: mysql2
  database: sac
  username: root 
  password: '1234'
  host: localhost

test:
  adapter: mysql2
  database: sac_test
  username: sac
  password: qir29sir
  host: 174.129.130.28

production:
  adapter: mysql2
  #database: sac
  database: sac_dev
  username: sac
  password: qir29sir
  host: localhost

cucumber:
  adapter: mysql2
  database: sac_test
  username: sac
  password: qir29sir
  host: 174.129.130.28
